const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'lib', 'learnWords.ts');
let content = fs.readFileSync(filePath, 'utf8');

// Remove the closing ];\n from the end
content = content.trimEnd();
if (content.endsWith('];')) {
  content = content.slice(0, -2);
} else if (content.endsWith('],')) {
  content = content.slice(0, -1);
}

const extraWords = `
  // ── More Everyday Vocabulary ──
  { word: "accomplish", meaning: "पूरा करना", example: "She accomplished her goal in record time." },
  { word: "acquire", meaning: "प्राप्त करना", example: "He acquired new skills during the training." },
  { word: "admire", meaning: "प्रशंसा करना", example: "I admire her dedication to work." },
  { word: "advance", meaning: "आगे बढ़ना", example: "Technology continues to advance rapidly." },
  { word: "affection", meaning: "स्नेह", example: "She showed great affection for her pet." },
  { word: "allocate", meaning: "आवंटित करना", example: "The budget was allocated carefully." },
  { word: "ambition", meaning: "महत्वाकांक्षा", example: "His ambition drove him to work harder." },
  { word: "amend", meaning: "संशोधित करना", example: "The law was amended by parliament." },
  { word: "ample", meaning: "पर्याप्त", example: "There is ample time to finish the task." },
  { word: "anticipate", meaning: "पूर्वानुमान लगाना", example: "We anticipate a large crowd at the event." },
  { word: "appease", meaning: "शांत करना", example: "He tried to appease the angry customer." },
  { word: "applaud", meaning: "तालियाँ बजाना", example: "The audience applauded loudly." },
  { word: "arbitrary", meaning: "मनमाना", example: "The decision seemed arbitrary and unfair." },
  { word: "ardent", meaning: "उत्साही", example: "She is an ardent fan of classical music." },
  { word: "aspire", meaning: "लालसा रखना", example: "He aspires to become a doctor." },
  { word: "assertive", meaning: "दृढ़", example: "She learned to be more assertive at work." },
  { word: "assume", meaning: "मान लेना", example: "Do not assume that everything is fine." },
  { word: "attentive", meaning: "ध्यानशील", example: "Students must be attentive during lectures." },
  { word: "authoritative", meaning: "आधिकारिक", example: "She gave an authoritative answer." },
  { word: "autonomy", meaning: "स्वायत्तता", example: "Children need some autonomy to develop." },
  { word: "awe", meaning: "विस्मय", example: "The view filled us with awe." },
  { word: "balance", meaning: "संतुलन", example: "Maintain a balance between work and rest." },
  { word: "barrier", meaning: "बाधा", example: "Language can be a barrier to communication." },
  { word: "benchmark", meaning: "मानक", example: "This sets a new benchmark for excellence." },
  { word: "bias", meaning: "पक्षपात", example: "Avoid bias when making decisions." },
  { word: "blueprint", meaning: "खाका", example: "The architect showed us the blueprint." },
  { word: "brainstorm", meaning: "विचार-मंथन", example: "Let us brainstorm ideas for the project." },
  { word: "calibrate", meaning: "समायोजित करना", example: "Calibrate the instrument before using it." },
  { word: "capacity", meaning: "क्षमता", example: "The stadium has a capacity of 50,000." },
  { word: "capitalize", meaning: "लाभ उठाना", example: "We should capitalize on this opportunity." },
  { word: "clarify", meaning: "स्पष्ट करना", example: "Please clarify your question." },
  { word: "collaborate", meaning: "मिलकर काम करना", example: "The two companies decided to collaborate." },
  { word: "compelling", meaning: "प्रेरक", example: "She gave a compelling argument." },
  { word: "compensate", meaning: "मुआवजा देना", example: "He was compensated for his extra work." },
  { word: "competent", meaning: "सक्षम", example: "She is a very competent engineer." },
  { word: "competitive", meaning: "प्रतिस्पर्धी", example: "The market is very competitive." },
  { word: "comprehend", meaning: "समझना", example: "It is hard to comprehend the scale of the problem." },
  { word: "conform", meaning: "अनुरूप होना", example: "Students must conform to school rules." },
  { word: "confront", meaning: "सामना करना", example: "She confronted her bully at school." },
  { word: "consolidate", meaning: "मजबूत करना", example: "We need to consolidate our position." },
  { word: "contemplate", meaning: "सोच-विचार करना", example: "He contemplated quitting his job." },
  { word: "contradict", meaning: "खंडन करना", example: "Your actions contradict your words." },
  { word: "cultivate", meaning: "विकसित करना", example: "Cultivate good habits from childhood." },
  { word: "dedicate", meaning: "समर्पित करना", example: "She dedicated her book to her parents." },
  { word: "defend", meaning: "रक्षा करना", example: "He defended his thesis successfully." },
  { word: "defer", meaning: "स्थगित करना", example: "The meeting was deferred to next week." },
  { word: "defy", meaning: "चुनौती देना", example: "She defied all expectations." },
  { word: "delegate", meaning: "सौंपना", example: "A good manager knows how to delegate tasks." },
  { word: "deliver", meaning: "पूरा करना", example: "She delivered an inspiring speech." },
  { word: "denote", meaning: "संकेत करना", example: "The red color denotes danger." },
  { word: "derive", meaning: "निकालना", example: "We derive energy from food." },
  { word: "desirable", meaning: "वांछनीय", example: "Honesty is a desirable quality." },
  { word: "detect", meaning: "पता लगाना", example: "Dogs can detect drugs easily." },
  { word: "differentiate", meaning: "अंतर करना", example: "Can you differentiate the two products?" },
  { word: "diminish", meaning: "कम करना", example: "Nothing can diminish her spirit." },
  { word: "disclose", meaning: "प्रकट करना", example: "He refused to disclose his identity." },
  { word: "dominate", meaning: "प्रभावित करना", example: "She dominated the competition." },
  { word: "dynamic", meaning: "गतिशील", example: "The market is very dynamic." },
  { word: "elaborate", meaning: "विस्तृत करना", example: "Can you elaborate on that point?" },
  { word: "empower", meaning: "शक्ति देना", example: "Education empowers people." },
  { word: "enhance", meaning: "बेहतर बनाना", example: "This course will enhance your skills." },
  { word: "establish", meaning: "स्थापित करना", example: "He established a successful company." },
  { word: "execute", meaning: "निष्पादित करना", example: "Execute the plan carefully." },
  { word: "exemplary", meaning: "आदर्श", example: "She showed exemplary behavior." },
  { word: "exhaust", meaning: "थका देना", example: "Do not exhaust all your resources." },
  { word: "exhibit", meaning: "प्रदर्शित करना", example: "She exhibited great courage." },
  { word: "expose", meaning: "उजागर करना", example: "The investigation exposed the corruption." },
  { word: "extend", meaning: "बढ़ाना", example: "Can you extend the deadline by a week?" },
  { word: "facilitate", meaning: "सुगम बनाना", example: "Technology facilitates communication." },
  { word: "flourish", meaning: "फलना-फूलना", example: "The business began to flourish." },
  { word: "formulate", meaning: "तैयार करना", example: "We need to formulate a new strategy." },
  { word: "foundation", meaning: "नींव", example: "Education is the foundation of success." },
  { word: "functional", meaning: "कार्यात्मक", example: "The machine is now fully functional." },
  { word: "global", meaning: "वैश्विक", example: "Climate change is a global concern." },
  { word: "harness", meaning: "उपयोग करना", example: "We must harness renewable energy." },
  { word: "identify", meaning: "पहचानना", example: "Can you identify the problem?" },
  { word: "implement", meaning: "लागू करना", example: "Implement the new policy from Monday." },
  { word: "imply", meaning: "इशारा करना", example: "What do you imply by that remark?" },
  { word: "impose", meaning: "थोपना", example: "Do not impose your views on others." },
  { word: "incentive", meaning: "प्रोत्साहन", example: "Bonuses act as an incentive for employees." },
  { word: "incorporate", meaning: "शामिल करना", example: "Incorporate feedback into your work." },
  { word: "infer", meaning: "अनुमान लगाना", example: "We can infer a lot from his silence." },
  { word: "inhibit", meaning: "रोकना", example: "Fear can inhibit your growth." },
  { word: "innovate", meaning: "नवाचार करना", example: "Companies must innovate to survive." },
  { word: "integrate", meaning: "एकीकृत करना", example: "We need to integrate the new system." },
  { word: "interpret", meaning: "व्याख्या करना", example: "How do you interpret this law?" },
  { word: "intervene", meaning: "हस्तक्षेप करना", example: "The government had to intervene." },
  { word: "introduce", meaning: "परिचय कराना", example: "Let me introduce you to my colleague." },
  { word: "launch", meaning: "शुरू करना", example: "They launched a new product today." },
  { word: "leverage", meaning: "लाभ उठाना", example: "Leverage your strengths." },
  { word: "liable", meaning: "जिम्मेदार", example: "He is liable for the damages." },
  { word: "maintain", meaning: "बनाए रखना", example: "Maintain a healthy lifestyle." },
  { word: "maximize", meaning: "अधिकतम करना", example: "Maximize your productivity." },
  { word: "mediate", meaning: "मध्यस्थता करना", example: "A lawyer mediated the dispute." },
  { word: "minimize", meaning: "कम करना", example: "Minimize waste in production." },
  { word: "mobilize", meaning: "जुटाना", example: "Mobilize resources for the project." },
  { word: "modify", meaning: "बदलना", example: "You may need to modify your plan." },
  { word: "navigate", meaning: "रास्ता ढूँढना", example: "Navigate through the challenges of life." },
  { word: "nurture", meaning: "पोषित करना", example: "Nurture your talent with practice." },
  { word: "optimize", meaning: "अनुकूलित करना", example: "Optimize your daily routine." },
  { word: "oversee", meaning: "निगरानी करना", example: "She oversees the entire department." },
  { word: "participate", meaning: "भाग लेना", example: "Everyone should participate in the event." },
  { word: "perform", meaning: "प्रदर्शन करना", example: "She performed exceptionally well." },
  { word: "pioneer", meaning: "अग्रदूत", example: "She was a pioneer in computing." },
  { word: "predict", meaning: "भविष्यवाणी करना", example: "It is hard to predict the weather." },
  { word: "preserve", meaning: "संरक्षित करना", example: "We must preserve our forests." },
  { word: "prevent", meaning: "रोकना", example: "Prevention is better than cure." },
  { word: "prioritize", meaning: "प्राथमिकता देना", example: "Prioritize your most important tasks." },
  { word: "promote", meaning: "बढ़ावा देना", example: "Promote healthy eating habits." },
  { word: "propose", meaning: "प्रस्ताव देना", example: "She proposed a new solution." },
  { word: "prove", meaning: "साबित करना", example: "Prove your worth with your work." },
  { word: "publish", meaning: "प्रकाशित करना", example: "She published her first novel at age 30." },
  { word: "realize", meaning: "महसूस करना", example: "I realized my mistake too late." },
  { word: "rebuild", meaning: "फिर से बनाना", example: "They rebuilt the city after the earthquake." },
  { word: "recruit", meaning: "भर्ती करना", example: "We are recruiting new team members." },
  { word: "refine", meaning: "परिष्कृत करना", example: "Refine your writing by editing carefully." },
  { word: "regulate", meaning: "नियमन करना", example: "The government regulates the market." },
  { word: "reinforce", meaning: "मजबूत करना", example: "Reinforce positive behavior with rewards." },
  { word: "resolve", meaning: "हल करना", example: "Let us resolve this conflict peacefully." },
  { word: "respect", meaning: "सम्मान", example: "Show respect to your elders." },
  { word: "restore", meaning: "बहाल करना", example: "Restore the old building to its former glory." },
  { word: "retain", meaning: "बनाए रखना", example: "The company wants to retain its best employees." },
  { word: "reveal", meaning: "प्रकट करना", example: "She revealed the truth at last." },
  { word: "revise", meaning: "संशोधित करना", example: "Revise your essay for grammar errors." },
  { word: "risk", meaning: "जोखिम", example: "Every investment carries some risk." },
  { word: "robust", meaning: "मजबूत", example: "The company has a robust financial plan." },
  { word: "scale", meaning: "पैमाना", example: "The scale of the disaster was shocking." },
  { word: "secure", meaning: "सुरक्षित करना", example: "Secure your passwords with strong codes." },
  { word: "seek", meaning: "खोजना", example: "Always seek knowledge." },
  { word: "sensitive", meaning: "संवेदनशील", example: "Be sensitive to others' feelings." },
  { word: "specify", meaning: "निर्दिष्ट करना", example: "Please specify the exact time of arrival." },
  { word: "standardize", meaning: "मानक बनाना", example: "We need to standardize the process." },
  { word: "strategic", meaning: "रणनीतिक", example: "She made a strategic decision." },
  { word: "substitute", meaning: "विकल्प", example: "Honey is a good substitute for sugar." },
  { word: "summarize", meaning: "सारांश देना", example: "Can you summarize the chapter?" },
  { word: "surpass", meaning: "पार करना", example: "She surpassed all expectations." },
  { word: "sustainable", meaning: "टिकाऊ", example: "We need sustainable development." },
  { word: "tackle", meaning: "निपटना", example: "Tackle the hardest problems first." },
  { word: "transform", meaning: "परिवर्तित करना", example: "Education can transform lives." },
  { word: "transition", meaning: "परिवर्तन", example: "The transition to a new system takes time." },
  { word: "transmit", meaning: "प्रसारित करना", example: "Diseases can be transmitted by touch." },
  { word: "trigger", meaning: "शुरू करना", example: "Stress can trigger various health problems." },
  { word: "unify", meaning: "एकजुट करना", example: "Music can unify people across borders." },
  { word: "utilize", meaning: "उपयोग करना", example: "Utilize your time wisely." },
  { word: "verify", meaning: "सत्यापित करना", example: "Please verify the information before sharing." },
  { word: "visualize", meaning: "कल्पना करना", example: "Visualize your success before achieving it." },
  { word: "witness", meaning: "गवाह", example: "He witnessed the entire accident." },
  // ── Science & Nature ──
  { word: "absorb", meaning: "अवशोषित करना", example: "Plants absorb sunlight through their leaves." },
  { word: "adaptation", meaning: "अनुकूलन", example: "Camels are an example of desert adaptation." },
  { word: "altitude", meaning: "ऊंचाई", example: "The altitude of Leh is very high." },
  { word: "anatomy", meaning: "शरीर रचना", example: "She is studying anatomy in medical school." },
  { word: "carbon", meaning: "कार्बन", example: "Carbon dioxide is a greenhouse gas." },
  { word: "civilization", meaning: "सभ्यता", example: "The Harappan civilization was very advanced." },
  { word: "climate", meaning: "जलवायु", example: "Climate change is a global challenge." },
  { word: "condensation", meaning: "संघनन", example: "Condensation forms on cold glass." },
  { word: "conservation", meaning: "संरक्षण", example: "Wildlife conservation is crucial." },
  { word: "density", meaning: "घनत्व", example: "Iron has a higher density than wood." },
  { word: "dissolve", meaning: "घुलना", example: "Sugar dissolves easily in water." },
  { word: "drought", meaning: "सूखा", example: "The drought affected millions of farmers." },
  { word: "ecosystem", meaning: "पारिस्थितिकी तंत्र", example: "The rainforest is a complex ecosystem." },
  { word: "emission", meaning: "उत्सर्जन", example: "Reduce carbon emissions to fight climate change." },
  { word: "erosion", meaning: "क्षरण", example: "Soil erosion damages farmland." },
  { word: "evaporation", meaning: "वाष्पीकरण", example: "Evaporation of water forms clouds." },
  { word: "evolution", meaning: "विकास", example: "Darwin studied the theory of evolution." },
  { word: "extinct", meaning: "विलुप्त", example: "Dinosaurs went extinct millions of years ago." },
  { word: "fossil", meaning: "जीवाश्म", example: "They found a fossil of an ancient fish." },
  { word: "friction", meaning: "घर्षण", example: "Friction causes heat when surfaces rub." },
  { word: "glacier", meaning: "हिमनद", example: "The glacier is melting due to global warming." },
  { word: "gravity", meaning: "गुरुत्वाकर्षण", example: "Gravity keeps us on the ground." },
  { word: "habitat", meaning: "प्राकृतिक वास", example: "Deforestation destroys animal habitats." },
  { word: "hemisphere", meaning: "गोलार्ध", example: "India is in the northern hemisphere." },
  { word: "hormone", meaning: "हार्मोन", example: "Growth hormones affect your height." },
  { word: "humidity", meaning: "आर्द्रता", example: "The humidity in Mumbai is very high." },
  { word: "immune", meaning: "प्रतिरक्षित", example: "A healthy body is immune to many diseases." },
  { word: "latitude", meaning: "अक्षांश", example: "India lies at a tropical latitude." },
  { word: "membrane", meaning: "झिल्ली", example: "The cell membrane controls what enters the cell." },
  { word: "migration", meaning: "प्रवास", example: "Bird migration is a natural phenomenon." },
  { word: "molecule", meaning: "अणु", example: "A water molecule has two hydrogen atoms." },
  { word: "mutation", meaning: "उत्परिवर्तन", example: "Genetic mutations can cause disease." },
  { word: "neuron", meaning: "न्यूरॉन", example: "Neurons transmit signals to the brain." },
  { word: "nutrient", meaning: "पोषक तत्व", example: "Vegetables are rich in nutrients." },
  { word: "orbit", meaning: "कक्षा", example: "The Earth orbits the Sun." },
  { word: "organism", meaning: "जीव", example: "Humans are complex organisms." },
  { word: "photosynthesis", meaning: "प्रकाश संश्लेषण", example: "Plants make food through photosynthesis." },
  { word: "pollution", meaning: "प्रदूषण", example: "Air pollution is a major health concern." },
  { word: "predator", meaning: "शिकारी", example: "The lion is a top predator." },
  { word: "protein", meaning: "प्रोटीन", example: "Eat protein-rich foods for muscle growth." },
  { word: "radiation", meaning: "विकिरण", example: "UV radiation can cause skin cancer." },
  { word: "recycle", meaning: "पुनर्चक्रण करना", example: "Recycle paper, glass, and plastic." },
  { word: "renewable", meaning: "नवीकरणीय", example: "Solar energy is a renewable resource." },
  { word: "sediment", meaning: "तलछट", example: "The river carried sediment to the sea." },
  { word: "species", meaning: "प्रजाति", example: "There are millions of species on Earth." },
  { word: "tsunami", meaning: "सुनामी", example: "The tsunami caused massive destruction." },
  { word: "vaccine", meaning: "टीका", example: "Get vaccinated to prevent diseases." },
  { word: "velocity", meaning: "वेग", example: "The velocity of the car increased rapidly." },
  { word: "vibration", meaning: "कंपन", example: "Sound travels through vibrations in the air." },
  { word: "wavelength", meaning: "तरंग दैर्ध्य", example: "Different colors have different wavelengths." },
  // ── Business & Finance ──
  { word: "acquisition", meaning: "अधिग्रहण", example: "The company acquisition was completed." },
  { word: "audit", meaning: "लेखापरीक्षा", example: "The company undergoes an annual audit." },
  { word: "brand", meaning: "ब्रांड", example: "Build a strong personal brand." },
  { word: "commodity", meaning: "वस्तु", example: "Gold is a valuable commodity." },
  { word: "compliance", meaning: "अनुपालन", example: "Ensure compliance with safety regulations." },
  { word: "consumer", meaning: "उपभोक्ता", example: "Consumer demand drives the economy." },
  { word: "contract", meaning: "अनुबंध", example: "Sign the contract before starting work." },
  { word: "currency", meaning: "मुद्रा", example: "The Indian currency is the Rupee." },
  { word: "deficit", meaning: "घाटा", example: "The government has a budget deficit." },
  { word: "depreciation", meaning: "मूल्यह्रास", example: "Cars lose value through depreciation." },
  { word: "dividend", meaning: "लाभांश", example: "Shareholders receive dividends annually." },
  { word: "equity", meaning: "हिस्सेदारी", example: "She bought equity in the startup." },
  { word: "expenditure", meaning: "व्यय", example: "Control your monthly expenditure." },
  { word: "franchise", meaning: "फ्रेंचाइज", example: "He opened a fast-food franchise." },
  { word: "inflation", meaning: "मुद्रास्फीति", example: "Inflation makes everyday goods expensive." },
  { word: "infrastructure", meaning: "बुनियादी ढांचा", example: "India is investing in its infrastructure." },
  { word: "inventory", meaning: "भंडार", example: "Update the inventory every week." },
  { word: "invest", meaning: "निवेश करना", example: "Invest in your education." },
  { word: "liability", meaning: "देनदारी", example: "Know your legal liabilities." },
  { word: "margin", meaning: "मार्जिन", example: "The profit margin increased this quarter." },
  { word: "merger", meaning: "विलय", example: "The merger of two banks was announced." },
  { word: "mortgage", meaning: "बंधक", example: "They took a mortgage to buy the house." },
  { word: "overhead", meaning: "उपरिव्यय", example: "Reduce overhead costs to increase profit." },
  { word: "pension", meaning: "पेंशन", example: "He receives a pension after retirement." },
  { word: "portfolio", meaning: "पोर्टफोलियो", example: "Diversify your investment portfolio." },
  { word: "productivity", meaning: "उत्पादकता", example: "Increase productivity with better tools." },
  { word: "profit", meaning: "लाभ", example: "The company made a huge profit this year." },
  { word: "quota", meaning: "कोटा", example: "Each department has a sales quota." },
  { word: "recession", meaning: "मंदी", example: "The economy entered a recession last year." },
  { word: "revenue", meaning: "राजस्व", example: "The company's revenue doubled this year." },
  { word: "startup", meaning: "स्टार्टअप", example: "She founded a successful startup." },
  { word: "subsidy", meaning: "सब्सिडी", example: "Farmers receive government subsidies." },
  { word: "surplus", meaning: "अधिशेष", example: "There is a food surplus this season." },
  { word: "tariff", meaning: "शुल्क", example: "The tariff on imported goods increased." },
  { word: "transaction", meaning: "लेनदेन", example: "Track every financial transaction carefully." },
  { word: "turnover", meaning: "कारोबार", example: "The annual turnover exceeded one crore." },
  { word: "welfare", meaning: "कल्याण", example: "The government promotes social welfare." },
];

`;

// Remove trailing comma from last entry if needed and append
content = content + '\n' + extraWords.trim() + '\n];\n';
fs.writeFileSync(filePath, content, 'utf8');
console.log('Done! Counting words...');
const count = (content.match(/\{ word:/g) || []).length;
console.log('Total words:', count);
